Refactor packagename
LabyMod/ultralight-java pull request #8
Opened 2020-08-28 16:20 UTC by xiantiel

Closes #5

2020-08-31 12:32 UTC, PublicByte requested changes
This PR contains unrelated changes ([add dummys commit](https://github.com/LabyMod/ultralight-java/pull/8/commits/14a714041560daa16a248a5b188ccdfeef4f37f6)), such as creating dummy methods. Please submit a separate PR for these changes (or none at all because they are dummy methods and do nothing).

2020-08-31 12:32 UTC, PublicByte commented on ultralight-java-databind/src/main/java/net/labymedia/ultralight/containers/JavascriptFunction.java
> +
Unrelated change.

2020-08-31 12:32 UTC, PublicByte commented on ultralight-java-databind/src/main/java/net/labymedia/ultralight/containers/JavascriptFunction.java
> +    }
Unrelated change.

2020-08-31 12:46 UTC, PublicByte commented
Also, this PR refers to a closed issue. Consider creating a new issue or open said issue.

2020-09-20 12:30 UTC, Janrupf commented
Has been done in place.

2020-09-20 12:30 UTC, closed without merging